package net.runelite.client.plugins.oneclickwintertodt

enum class States {
    IDLE,
    DEPOSIT_ITEMS,
    WOODCUTTING,
    FLETCHING,
    EAT,
    NEED_HAMMER,
    NEED_KNIFE,
    NEED_TINDERBOX,
    GO_TO_BRAZIER,
    LIGHT_BRAZIER,
    FIREMAKING,
    LEAVE_DOOR,
    CONFIRM_EXIT,
    BANK,
    WITHDRAW_FOOD,
    RETURN_INSIDE,
    REPAIR,
    NEED_VIAL,
    PICK_HERB,
    MIX_VIAL,
    HEAL_PYROMANCER,
    WALK_TO_POS,
    WAIT_TO_LEAVE,
    MOVE_TO_HIDEY_HOLE,
    SAFE,
    ENABLE_RUN
}