package net.runelite.client.plugins.oneclicklavas

enum class States {
    IDLE,
    NEED_STAMINA,
    NEED_DEPOSIT,
    NEED_NECKLACE,
    DRINK_STAMINA,
    PREPARE_TO_TELEPORT,
    TELEPORT_FROM_BANK,
    ENTER_RUINS,
    IMBUE,
    CRAFT_RUNES,
    EMPTY_POUCHES,
    TELEPORT_TO_BANK,
    NEED_ESSENCE,
    FILL_POUCH,
    CLOSE_BANK,
    OPEN_BANK,
    DESTROY_NECKLACE,
    CONFIRM_DESTROY
}